model_config_list {
  config {
    name: "failure_predictor"
    base_path: "/models/failure_predictor"
    model_platform: "tensorflow"
    model_version_policy: { latest { num_versions: 2 } }
  }
}
